commodities = {
    "Raw Materials": [
        {"name": "Primordial Sludge", "value": 5, "description": "Hypercompressed CHON-rich goo left over from pre-stellar planetary formation, used in the creation of prebiotic nanoforges."},
        {"name": "Firstfire Char", "value": 5, "description": "Carbon remnants from the first ignition of ancient stars; imbued with rare isotopic properties ideal for quantum-reactive technologies."},
        {"name": "Crysogen Blood", "value": 5, "description": "Semi-organic cryogenic liquid rumored to predate starbirths themselves; contains unknown carbon-hydrogen matrix forms."},
        {"name": "Ashen Marrow", "value": 5, "description": "Deep-subterranean organic ash deposits, rich in complex hydrocarbons and used in the manufacture of polymer alloys."},
        {"name": "Gravossils", "value": 5, "description": "Fossilized remains of high-gravity megafauna; their carbonized bones are repurposed into ship-grade armor plating."},
        {"name": "Black Bloom Spores", "value": 5, "description": "Dense atmospheric particulates that propagate carbon-extraction ecosystems; used in environmental restoration and energy farming."},
        {"name": "Diamass Lattices", "value": 5, "description": "Artificial diamond composites layered with quantum resonance nodes; foundational in gravity-wave engines."},
        {"name": "Neurocarbon Foils", "value": 5, "description": "Electrically sensitive graphene variants used in thought-responsive circuitry."},
        {"name": "Charroot Extract", "value": 5, "description": "Biogenic carbon concentrate sourced from ancient tree-analog forests on terraformed planets; revered for its binding strength."},
        {"name": "Aetheron Vapors", "value": 5, "description": "Rare, high-energy atmospheric gases infused with Ether Magic, harvested from semi-sentient cloud masses."},
        {"name": "Methylox Pools", "value": 5, "description": "Highly volatile hydrocarbon lakes found on exo-moons; used for low-temperature propulsion and biochemical labs."},
        {"name": "Sublime Ammonite", "value": 5, "description": "Superfluid ammonia derivatives used to support extreme-temperature colonies and exobiological experiments."},
        {"name": "Proto-Amino Pools", "value": 5, "description": "Concentrations of primordial organic molecules collected from young planetary oceans; essential for genetic engineering foundations."},
        {"name": "Polyether Mists", "value": 5, "description": "Naturally occurring long-chain polymers suspended in breathable atmospheres; used in atmospheric processors and synthetics."},
        {"name": "Solvoplant Resin", "value": 5, "description": "Highly adaptable organic resin that can chemically fuse disparate materials; a living industrial adhesive."},
        {"name": "Chimeric Fibers", "value": 5, "description": "Cross-species organic materials woven into hyperelastic biological cloths or regenerative armor underlayers."},
        {"name": "Lignofoam Blocks", "value": 5, "description": "Ultra-lightweight, cellulose-based rigid structures grown from engineered arboreal systems on orbital greenworlds."},
        {"name": "Plasmwood", "value": 5, "description": "A hyper-conductive plant-derived material capable of sustaining plasma currents without structural loss."},
        {"name": "Carboxite Slabs", "value": 5, "description": "Dense carbon structures harvested from black-dwarf mining stations; essential for ultra-strong composites and energy absorption tech."},
        {"name": "Hydron Slurry", "value": 5, "description": "Supercooled hydrogen-based fluid, stable under extreme pressures; used in fusion engines and bio-manufacturing."},
        {"name": "Oxyweave Fiber", "value": 5, "description": "Microscopic oxygen-threaded lattices, flexible yet resilient; essential for life support systems and eco-terraforming fabrics."},
        {"name": "Nitrocryst", "value": 5, "description": "Naturally forming nitrogen crystals found near volatile gas giants; used in high-energy chemical synthesis and pharmaceuticals."},
        {"name": "Aether Carbide", "value": 5, "description": "Carbonized material resonant with etheric fields, enhancing structural integrity in phase-shifted environments."},
        {"name": "Biochar Resin", "value": 5, "description": "Semi-living carbonous secretion from engineered megaflora, prized for biotechnical construction and adaptive armors."},
        {"name": "Hydrophage Gels", "value": 5, "description": "Water-absorbing compounds synthesized for arid colonization projects and hydroponic vaults."},
        {"name": "Cryonite Dust", "value": 5, "description": "Frozen gas particulates containing reactive hydrocarbons; gathered from comet fields and useful for synthetic biology."},
        {"name": "VitaCarbon Strands", "value": 5, "description": "Living carbon-filament threads that regenerate when damaged; integrated into smart suits and repairable ship hulls."},
        {"name": "Zerite Crystals", "value": 5, "description": "Essential for etheric energy amplification."},
        {"name": "Crythium Ore", "value": 5, "description": "High-conductivity mineral used in quantum computing hardware."},
        {"name": "Phasemetal", "value": 5, "description": "A rare alloy that can exist in multiple phases of matter."},
        {"name": "Ionwood", "value": 5, "description": "Organic conductive material grown in artificial orbit-forests."},
        {"name": "Voidglass Shards", "value": 5, "description": "Transdimensional glass fragments used in sensor arrays."},
        {"name": "Quantum Sand", "value": 5, "description": "Microscopic particles with variable mass states."},
        {"name": "Chrono-silt", "value": 5, "description": "Sediment collected from temporal rift zones."},
        {"name": "Gravite", "value": 5, "description": "A dense mineral used for artificial gravity systems."},
        {"name": "Nullstone", "value": 5, "description": "An antimagic material that negates Etheric fields."},
        {"name": "Living Ore", "value": 5, "description": "Semi-sentient mineral that reconfigures based on purpose."}
    ],
    "Bio-Materials and Agriculture": [
        {"name": "Ethergrain", "value": 5, "description": "Nutrient-rich crop enhanced by ambient Ether Magic."},
        {"name": "Dreamroot", "value": 5, "description": "A plant that induces controlled lucid dream states."},
        {"name": "Synthmeat Matrix", "value": 5, "description": "Lab-grown protein with programmable textures."},
        {"name": "Sporemilk", "value": 5, "description": "Nutrient-dense fluid produced by Mycelioid biome-farms."},
        {"name": "Glowfruit", "value": 5, "description": "Edible bioluminescent produce from Luminaut greenworlds."},
        {"name": "Singecorn", "value": 5, "description": "Flame-resistant hybrid cereal grain from high-radiation planets."},
        {"name": "Coraline", "value": 5, "description": "Living coral used for architecture and regenerative medicine."},
        {"name": "Plasma Honey", "value": 5, "description": "Produced by heat-immune bee analogs; used in energy tonics."},
        {"name": "Spirathorn", "value": 5, "description": "Aromatic herb with mild psionic effects when brewed."},
        {"name": "Skyalgae", "value": 5, "description": "High-oxygen algae cultivated in floating gas colonies."}
    ],
    "Technological Goods": [
        {"name": "Neural Threadwire", "value": 5, "description": "High-speed organic-computational interface cable."},
        {"name": "Chrono-ink", "value": 5, "description": "Used to encode data visible only in specific time phases."},
        {"name": "Sentient Circuitry", "value": 5, "description": "AI-infused logic boards for living machines."},
        {"name": "Etherwave Transponders", "value": 5, "description": "Long-distance communication devices across dimensions."},
        {"name": "Quantum Keys", "value": 5, "description": "One-time-use decryption devices based on paired particles."},
        {"name": "Grav-Core Modules", "value": 5, "description": "Core components of artificial gravity engines."},
        {"name": "Polymorphic Plasteel", "value": 5, "description": "Programmable armor material used in adaptive suits."},
        {"name": "Temporal Batteries", "value": 5, "description": "Store and release time-based energy."},
        {"name": "Nanite Hives", "value": 5, "description": "Programmable swarms in containment for field repair or assembly."},
        {"name": "Subconscious OS Cores", "value": 5, "description": "Operating systems designed to interface with thought alone."}
    ],
    "Cultural and Luxury Goods": [
        {"name": "Aetherwine", "value": 5, "description": "A radiant, mildly intoxicating drink with vision-inducing properties."},
        {"name": "Harmonic Crystals", "value": 5, "description": "Emit soothing frequencies used in meditation and therapy."},
        {"name": "Starweave Fabric", "value": 5, "description": "Woven from matter harvested in solar flares; glows with energy."},
        {"name": "Singularity Artifacts", "value": 5, "description": "One-of-a-kind objects formed in micro black holes."},
        {"name": "Chrono-music Scrolls", "value": 5, "description": "Unfold melodies only perceivable in layered time."},
        {"name": "Galactic Pheromones", "value": 5, "description": "Designer scent stimulants tailored for interspecies interaction."},
        {"name": "Dreamtapestries", "value": 5, "description": "Interactive textiles that change based on emotion."},
        {"name": "Void Ink Tattoos", "value": 5, "description": "Animated tattoos powered by ambient etheric energy."},
        {"name": "Solar Glass Jewelry", "value": 5, "description": "Gathers and refracts stellar light into changing patterns."},
        {"name": "Emotion Sculptures", "value": 5, "description": "Biochemical art pieces that resonate with specific moods."}
    ],
    "Medical and Scientific": [
        {"name": "Cognitive Accelerants", "value": 5, "description": "Compounds that temporarily enhance thought processing."},
        {"name": "Neuro-regenerative Gel", "value": 5, "description": "Rebuilds damaged neural pathways."},
        {"name": "Panviral Antiserum", "value": 5, "description": "Adaptive vaccine base for known galactic pathogens."},
        {"name": "Bioplasmic Infusion Kits", "value": 5, "description": "Used to repair or augment organic tissue."},
        {"name": "Dimensional Anchors", "value": 5, "description": "Tools to maintain bodily coherence during multiverse travel."},
        {"name": "Etheric Alignment Salts", "value": 5, "description": "Stabilize internal energy channels before ritual or surgery."},
        {"name": "Temporal Regrowth Fluid", "value": 5, "description": "Stimulates cell regeneration in sync with local timeline."},
        {"name": "Astral Cortical Threads", "value": 5, "description": "Used to repair psychic damage to the mind."},
        {"name": "Void-Adapt Serums", "value": 5, "description": "Temporary genetic edits to survive low-reality zones."},
        {"name": "Symbiont Kits", "value": 5, "description": "Packages containing engineered organisms for internal augmentation."}
    ],
    "Advanced Energy Sources": [
        {"name": "Pulsecores", "value": 5, "description": "Compact fusion cells used in personal-scale devices."},
        {"name": "Etherium Flux Crystals", "value": 5, "description": "Self-recharging energy matrices attuned to etheric flow."},
        {"name": "Tachyon Solenoids", "value": 5, "description": "Used for propulsion and near-instantaneous data pulses."},
        {"name": "Solar Thread Coils", "value": 5, "description": "Woven strands that capture and store stellar radiation."},
        {"name": "Antigravium Nodes", "value": 5, "description": "Stabilized gravity-manipulation cores for hover tech."},
        {"name": "Psionic Capacitors", "value": 5, "description": "Store mental energy for use in telepathic technologies."},
        {"name": "Nullwave Cells", "value": 5, "description": "Emit localized fields that dampen all energy fluctuations."},
        {"name": "Nova Dust", "value": 5, "description": "Controlled remnant particles from stellar explosions used as boosters."},
        {"name": "Temporal Drift Plasmoids", "value": 5, "description": "Provide power in unstable time zones."},
        {"name": "Etherfire Gel", "value": 5, "description": "High-energy compound that burns in both vacuum and atmosphere."}
    ],
    "Cybernetic and AI Components": [
        {"name": "Synaptic Meshes", "value": 5, "description": "Interface layers between organics and machines."},
        {"name": "Hive Intellect Shards", "value": 5, "description": "Fragments of AI minds designed to assist users."},
        {"name": "Emotion Algorithms", "value": 5, "description": "Codified emotional routines for artificial life."},
        {"name": "Adaptive Retinal Lenses", "value": 5, "description": "Smart ocular implants that adjust for any condition."},
        {"name": "Micro-Sentience Bundles", "value": 5, "description": "Packaged proto-AI entities for task automation."},
        {"name": "Predictive Logic Crystals", "value": 5, "description": "Used in decision-making units for autonomous drones."},
        {"name": "Tactical Reflex Circuits", "value": 5, "description": "Enhances user reaction time through preemptive AI."},
        {"name": "Subdermal Logic Arrays", "value": 5, "description": "Embedded computing platforms for discreet use."},
        {"name": "Ether-AI Enclaves", "value": 5, "description": "Housed clusters of sentient quantum code for ship systems."},
        {"name": "Behavioral Echo Units", "value": 5, "description": "Devices that learn from users to simulate habits."}
    ],
    "Alien and Exotic Biological Goods": [
        {"name": "Mindleaves", "value": 5, "description": "Rare leaves that temporarily enhance memory recall."},
        {"name": "Voxworms", "value": 5, "description": "Symbiotic organisms that allow temporary translation of alien speech."},
        {"name": "Bio-ink Strains", "value": 5, "description": "Living ink used for dynamic document writing and encryption."},
        {"name": "Neural Coral Seeds", "value": 5, "description": "Grown in labs to enhance telepathic connectivity."},
        {"name": "Astral Mycelium Spores", "value": 5, "description": "Fungal spores with applications in dimensional sensing."},
        {"name": "Pherocells", "value": 5, "description": "Engineered cells that respond to emotion-specific hormones."},
        {"name": "Xeno-muscle Fibers", "value": 5, "description": "Used to repair or enhance organic tissue strength."},
        {"name": "Thorns of Evas", "value": 5, "description": "Hallucinogenic alien flora with ritualistic value."},
        {"name": "Sentient Moss", "value": 5, "description": "Bio-reactive covering used in healing or environmental sensors."},
        {"name": "Crystaline Spinepods", "value": 5, "description": "Alien fauna components used in stabilizing implants."}
    ],
    "Information and Cultural Datastreams": [
        {"name": "Memory Cubes", "value": 5, "description": "Encoded life experiences, used in historical research and entertainment."},
        {"name": "Consciousness Maps", "value": 5, "description": "Digital overlays of thought patterns used in cognitive studies."},
        {"name": "Fractal Lore Vessels", "value": 5, "description": "Contain complex, multilayered alien cultural records."},
        {"name": "Time-Sealed Journals", "value": 5, "description": "Writings encoded to unlock in specific futures."},
        {"name": "Neural Drama Sequences", "value": 5, "description": "Immersive stories injected directly into consciousness."},
        {"name": "Simculture Blueprints", "value": 5, "description": "Design files to recreate alien societies in simulation."},
        {"name": "Ethical Codices", "value": 5, "description": "Compilations of value systems from across species."},
        {"name": "Interdream Archives", "value": 5, "description": "Shared dream recordings used in diplomacy and therapy."},
        {"name": "Living Manuscripts", "value": 5, "description": "Texts that respond to questions and evolve with time."},
        {"name": "Pre-Singularity Data Keys", "value": 5, "description": "Obsolete but valuable formats containing ancient knowledge."}
    ],
    "Industrial and Structural Materials": [
        {"name": "Voidfoam", "value": 5, "description": "Expands into vacuum-resistant insulation."},
        {"name": "Phasefiber", "value": 5, "description": "Material that can shift density or hardness on command."},
        {"name": "Spectral Alloy", "value": 5, "description": "Nearly invisible material used in stealth construction."},
        {"name": "Chrono-lattice Panels", "value": 5, "description": "Building material that resists temporal distortion."},
        {"name": "Starforge Steel", "value": 5, "description": "Created in solar furnaces, nearly indestructible."},
        {"name": "Etherglass", "value": 5, "description": "Transparent but shielded against radiation and psychic intrusion."},
        {"name": "Dimensine", "value": 5, "description": "Shapeshifting smart matter for modular construction."},
        {"name": "Bio-Ceramic Matrix", "value": 5, "description": "Grown into custom forms, used in exo-armor and medtech."},
        {"name": "Reflective Gravfilm", "value": 5, "description": "Used on ships and suits to deflect mass-based weapons."},
        {"name": "Transductive Webbing", "value": 5, "description": "Wiring that functions across dimensional boundaries."}
    ],
    "Illegal or Restricted Substances": [
        {"name": "Chrono-Dust", "value": 5, "description": "Temporally unstable stimulant, banned in most systems."},
        {"name": "Etherlace", "value": 5, "description": "Addictive etheric enhancer used by rogue mages."},
        {"name": "Memory Theft Vials", "value": 5, "description": "Contains stolen consciousness fragments."},
        {"name": "Obscura Gel", "value": 5, "description": "Wipes digital and biological memory upon contact."},
        {"name": "Darkseed Nanites", "value": 5, "description": "Rogue AI-infused nanotech, used in sabotage."},
        {"name": "Paradox Shards", "value": 5, "description": "Crystalline objects from timeline collisions, highly dangerous."},
        {"name": "Shiver Ink", "value": 5, "description": "Used to falsify identity signatures across galaxies."},
        {"name": "Soulshade", "value": 5, "description": "Etheric substance used to hide spiritual presence."},
        {"name": "Null Whisper Chips", "value": 5, "description": "Illegal devices that mute sentient AI self-awareness."},
        {"name": "Reality Hack Keys", "value": 5, "description": "Open portals to unstable alternate timelines."}
    ],
    "Perishable Goods": [
        {"name": "Cryofruit Pulp", "value": 5, "description": "Genetically engineered fruit that only grows in cryogenic environments; must be kept at sub-zero temperatures to remain viable."},
        {"name": "Bioluminescent Fungi", "value": 5, "description": "Used for natural lighting and ambiance, common in underground colonies."},
        {"name": "Synthetic Meat Cultures", "value": 5, "description": "Engineered protein slabs ready for regeneration into full meals."},
        {"name": "Sporewine", "value": 5, "description": "A mildly psychoactive drink brewed from fungal spores; has a short shelf life."},
        {"name": "Atmospheric Coral Spores", "value": 5, "description": "Used in planetary terraforming to initiate oxygen-producing environments."},
        {"name": "Aqua-Rice Pods", "value": 5, "description": "Aquatic cereal grain grown in bio-hydroponic tanks."},
        {"name": "QuickCell Yeast", "value": 5, "description": "Rapid fermentation starter for nutrient production on long-haul ships."},
        {"name": "Nebulox Honey", "value": 5, "description": "A rare, fragrant nectar produced by cloud-floating pollinators on gas giants."},
        {"name": "Flash-Grown Vines", "value": 5, "description": "Fast-expanding vegetation used for environmental reclamation."},
        {"name": "Live Starfish-Root Cuttings", "value": 5, "description": "A delicacy and regenerative snack among aquatic species."}
    ],
    "Luxury Goods": [
        {"name": "Ether-Infused Perfumes", "value": 5, "description": "Scents blended with low-level Ether Magic to evoke emotions or memories."},
        {"name": "Living Paintings", "value": 5, "description": "Biotechnological art that subtly shifts based on viewer mood."},
        {"name": "Chrono-Crystals", "value": 5, "description": "Rare gems that resonate with specific timelines and occasionally reflect possible futures."},
        {"name": "Time-Aged Neural Liqueurs", "value": 5, "description": "Alcoholic concoctions aged in distorted time pockets for unique effects."},
        {"name": "Memory Candies", "value": 5, "description": "Edibles that replicate emotional memories when consumed."},
        {"name": "Stellar Silk", "value": 5, "description": "Woven from nanofibers cultured in zero-gravity, known for softness and radiant shimmer."},
        {"name": "Whale-Glass Vials", "value": 5, "description": "Made from ocean-dwelling megafauna bone-glass on water planets; highly prized for ritual use."},
        {"name": "Fractal Jewelry", "value": 5, "description": "Crystalline patterns infinitely recursive under magnification."},
        {"name": "Emotion-Tuned Instruments", "value": 5, "description": "Musical tools that alter tone based on player’s emotional state."},
        {"name": "Gravity-Woven Robes", "value": 5, "description": "Clothing that subtly adjusts personal gravitational fields for comfort and presence."}
    ],
    "Religious and Ceremonial Items": [
        {"name": "Prayer Stones of Entari", "value": 5, "description": "Resonant relics said to store spiritual echoes from extinct civilizations."},
        {"name": "Ether Scrolls", "value": 5, "description": "Bioluminescent membranes encoded with sacred light-language."},
        {"name": "Soul Chimes", "value": 5, "description": "Instruments that react to nearby consciousness levels, used in rites of passage."},
        {"name": "Spirit Ember Capsules", "value": 5, "description": "Tiny containers that hold purified etheric flames, symbolic in ceremonies."},
        {"name": "Starborn Incense", "value": 5, "description": "Aromatic compound harvested from comet trails, burned for transcendental rituals."},
        {"name": "Halo Glass Beads", "value": 5, "description": "Used in meditative practices; known to stabilize aura fields."},
        {"name": "Ceremonial Gravity Orbs", "value": 5, "description": "Floatable spheres used in low-gravity rituals to symbolize balance and motion."},
        {"name": "The Book of Voids", "value": 5, "description": "A blank ceremonial tome whose pages shift based on personal introspection."},
        {"name": "Echo Vestments", "value": 5, "description": "Robes embedded with sound-sensitive fibers that echo chants across realms."},
        {"name": "Blood-Map Totems", "value": 5, "description": "Encoded with genetic memory, used in ancestral lineage rituals."}
    ],
    "Military-Grade Items": [
        {"name": "Gravitic Blade Cores", "value": 5, "description": "Compact mass-enhancing tech that increases weapon momentum on impact."},
        {"name": "Pulse-Shield Emitters", "value": 5, "description": "Portable shields with fluctuating energy signatures to confuse tracking."},
        {"name": "Anti-Etheric Darts", "value": 5, "description": "Designed to disrupt Ether Magic users by severing flow temporarily."},
        {"name": "Sonic Veil Grenades", "value": 5, "description": "Deploys dissonant frequencies that disorient non-humanoid senses."},
        {"name": "Sentient Tactical Maps", "value": 5, "description": "Adaptive battlefield overlays that evolve with situational context."},
        {"name": "Phase-Cloaked Armor Weave", "value": 5, "description": "Armor embedded with short-range phase-shifting tech."},
        {"name": "Subdermal Reactor Charges", "value": 5, "description": "Implanted micro-reactors powering cybernetic war systems."},
        {"name": "Plasma Braid Whips", "value": 5, "description": "Energy-based melee weapons that arc unpredictably mid-swing."},
        {"name": "Voidglass Ammunition", "value": 5, "description": "Shards harvested from void realms, devastating on contact."},
        {"name": "Temporal Warp Charges", "value": 5, "description": "Limited-use explosives that reverse time in a 5-meter radius by 1.3 seconds."}
    ],
    "Miscellaneous Goods": [
        {"name": "Echo Seeds", "value": 5, "description": "Bio-resonant plants that mirror surrounding soundscapes as they grow."},
        {"name": "Data-Aura Charms", "value": 5, "description": "Wearables that filter information overload through quantum tagging."},
        {"name": "Telempathic Gloves", "value": 5, "description": "Allow haptic communication through subtle shifts in magnetic field."},
        {"name": "Grav-Skates", "value": 5, "description": "Footwear enabling precise manipulation of personal inertia fields."},
        {"name": "Language Spores", "value": 5, "description": "Fungus that temporarily rewires brain linguistics for instant translation."},
        {"name": "Lumen Bark", "value": 5, "description": "Light-emitting bark from the photon-rich forests of Miravax."},
        {"name": "Chrono-Dust", "value": 5, "description": "Fine particulate used in experimental time-anchoring technologies."},
        {"name": "Reality Anchors", "value": 5, "description": "Personal devices preventing dimensional drift during planar travel."},
        {"name": "Thought Crystals", "value": 5, "description": "Solidified bursts of pure cognition used in mental programming."},
        {"name": "Dream-Tide Ink", "value": 5, "description": "Used in tattoo rituals or art that shifts appearance during sleep."}
    ],
    "Temporal Goods": [
        {"name": "Chrono Crystals", "value": 5, "description": "Naturally occurring temporal resonance stones used in time-related tech."},
        {"name": "Stasis Fluid", "value": 5, "description": "A viscous liquid used for preserving matter in a timeless state."},
        {"name": "Looped Grain", "value": 5, "description": "A foodstuff caught in a microtime loop, never expiring."},
        {"name": "Time-Stretched Textiles", "value": 5, "description": "Garments that change appearance across time gradients."},
        {"name": "Paradox Seeds", "value": 5, "description": "Illegal plants that destabilize cause-effect relationships."}
    ],
    "Mental and Consciousness Commodities": [
        {"name": "Memory Wafers", "value": 5, "description": "Encoded experiences purchasable for consumption or upload."},
        {"name": "Synthetic Emotions", "value": 5, "description": "Engineered emotional states delivered via injectables or implants."},
        {"name": "Thought Fossils", "value": 5, "description": "Preserved cognitive remnants from extinct species."},
        {"name": "Dream Cores", "value": 5, "description": "Bottled lucid dreams from master dreamers or prophets."},
        {"name": "Cognitive Mirrors", "value": 5, "description": "Devices that project your thoughts for collaborative decision-making."}
    ],
    "Dimensional and Interplanar Goods": [
        {"name": "Phase Silk", "value": 5, "description": "Woven in a dimension with different physical laws, phasing in and out of visibility."},
        {"name": "Cross-Plane Glass", "value": 5, "description": "A material that allows vision into adjacent realities."},
        {"name": "Echo Matter", "value": 5, "description": "A substance that only exists in multiple dimensions simultaneously."},
        {"name": "Inverted Liquids", "value": 5, "description": "Fluids that behave opposite to local gravity or force."},
        {"name": "Planar Anchors", "value": 5, "description": "Tools that tether objects to one dimension across rift zones."}
    ],
    "Advanced Synthetic Goods": [
        {"name": "Nano-Slime", "value": 5, "description": "Programmable nanite gel for repair, construction, or ingestion."},
        {"name": "Bio-Stone", "value": 5, "description": "Living stone used in architecture that adjusts to temperature and weight."},
        {"name": "Transkin Membranes", "value": 5, "description": "Intelligent clothing that adapts to emotional and environmental states."},
        {"name": "Self-Replicating Lubricants", "value": 5, "description": "Maintenance compounds that regenerate themselves when depleted."},
        {"name": "Crystallized Neural Gel", "value": 5, "description": "Storage medium for AI consciousness migration."}
    ],
    "Psycho-Etheric Artifacts": [
        {"name": "Soul Ink", "value": 5, "description": "Used for tattoos or writing that responds to the wearer's mood and intent."},
        {"name": "Astral Strings", "value": 5, "description": "Tuned filaments that vibrate based on nearby consciousness."},
        {"name": "Mind Keys", "value": 5, "description": "Etheric tokens that unlock mental states or meditative dimensions."},
        {"name": "Echo Paint", "value": 5, "description": "Pigment that replays the emotional resonance of moments long past."},
        {"name": "Lament Glass", "value": 5, "description": "Windows that whisper the memories of places they once viewed."}
    ],
    "Cultural and Symbolic Items": [
        {"name": "Unity Coins", "value": 5, "description": "Artifacts minted during rare interspecies summits, traded as symbols of peace."},
        {"name": "Ceremonial Bone Scrolls", "value": 5, "description": "Recordings of extinct alien rites, considered sacred and irreplaceable."},
        {"name": "Memory Feathers", "value": 5, "description": "Grown from archivist birds; retain cultural knowledge in encoded light flashes."},
        {"name": "Ancestor Beads", "value": 5, "description": "Biotech relics tied to genetic memory of lost lineages."},
        {"name": "Linguistic Seeds", "value": 5, "description": "Encoded linguistic DNA used to regrow dead languages in neural implants."}
    ],
    "Terraforming and Environmental Engineering Goods": [
        {"name": "Atmosphere Catalysts", "value": 5, "description": "Crystalline compounds that rapidly alter gaseous compositions."},
        {"name": "Ocean Bloom Pellets", "value": 5, "description": "Biogenic capsules used to kickstart marine ecosystems."},
        {"name": "Root-Spine Trees", "value": 5, "description": "Planet-seeding flora that form root-planetary interfaces."},
        {"name": "ClimeShells", "value": 5, "description": "Rapid deployment pods that stabilize temperature and weather for colonists."},
        {"name": "Harmonic Fungus", "value": 5, "description": "Mycelial organisms tuned to planetary vibrations, used to regulate tectonic activity."}
    ],
    "Mythic and High-Value Relics": [
        {"name": "Pre-Singularity AI Cores", "value": 5, "description": "Rare, early-model artificial intelligences regarded as ancestors by modern AIs."},
        {"name": "Lost Emperors' Implants", "value": 5, "description": "High-value relics containing encrypted knowledge from extinct dynasties."},
        {"name": "Divine Echo Tablets", "value": 5, "description": "Regarded as religious relics, containing unknown mathematical truths."},
        {"name": "Chrono-Horns", "value": 5, "description": "Organic instruments that can freeze a moment when played correctly."},
        {"name": "Blackstone Coins", "value": 5, "description": "Mysterious currency minted from non-reflective material that drains light and heat."}
    ],
    "Educational and Learning Artifacts": [
        {"name": "Neural Tutor Nodes", "value": 5, "description": "Self-adaptive implants that teach by interfacing directly with the learner's brain."},
        {"name": "Cognitive Prism Lenses", "value": 5, "description": "Eyewear that translates complex theories into intuitive visual representations."},
        {"name": "Didactic Dust", "value": 5, "description": "Nanoparticles that embed structured lessons in air—absorbed via breath and interpreted in dreams."},
        {"name": "Chrono-Lesson Capsules", "value": 5, "description": "Time-dilated experiences where a subject can be learned over years in minutes of real time."},
        {"name": "Autodidact Seeds", "value": 5, "description": "Bio-synthetic nodules that evolve into personalized learning assistants."},
        {"name": "Sentient Whiteboards", "value": 5, "description": "Interactive surfaces that challenge, debate, and test the user in real time."},
        {"name": "Thoughtloop Cubes", "value": 5, "description": "Handheld devices that simulate philosophical dilemmas and cognitive feedback loops."},
        {"name": "LinguaCode Serums", "value": 5, "description": "Temporary chemical language infusions enabling instant fluency in over 3000 tongues."},
        {"name": "Aetheric Pedagogues", "value": 5, "description": "Holographic teachers encoded with multidimensional consciousness for guided instruction."},
        {"name": "Mnemonic Threads", "value": 5, "description": "Wearable memory augmentation fibers that bind concepts to emotional or sensory cues."},
        {"name": "Emotionally-Tuned Lectures", "value": 5, "description": "Recorded teachings that adjust tone and tempo based on the learner’s mood."},
        {"name": "Knowledge Spores", "value": 5, "description": "Bioluminescent fungi that emit ambient, low-bandwidth information through light frequencies."},
        {"name": "Quantum Reference Slates", "value": 5, "description": "Libraries compressed into quantum layers—readable only by sentient or near-sentient minds."},
        {"name": "Didactic Symphonies", "value": 5, "description": "Orchestral compositions used to encode complex learning through vibrational absorption."},
        {"name": "HoloText Tomes", "value": 5, "description": "Books that reconfigure themselves to match the user’s cognitive level, background, and worldview."}
    ]
}
